# Example configuration for tiles-proxy-cache
# Demonstrates various tile service configurations including:
# - Standard image tiles (PNG, JPG, WebP)
# - LERC elevation data processing
# - High-resolution tiles
# - Custom authentication and headers

# Satellite imagery service
World_Imagery:
  path: "/wi/:z/:x/:y"
  target: "https://example-satellite.com/imagery/tiles/{z}/{y}/{x}.png"
  minzoom: 1
  maxzoom: 20
  miss_timeout: 300        # 5 minutes timeout for error tiles
  miss_max_records: 10000  # max miss records before cleanup
  headers:
    request:
      User-Agent: "TileProxy/1.0"
    response:
      Cache-Control:
        max-age:
          hit: 86400      # 24 hours
          miss: 300       # 5 minutes
  query_params:
    # apikey: "your-satellite-api-key"  # Optional API key
  mbtiles_file: "world_imagery.mbtiles"
  metadata:
    bounds: "-180,-85.0511,180,85.0511"
    center: "0,0,3"
    type: "baselayer"  # baselayer | overlay
  autoscan:
    enabled: false
    daily_limit: 5000
    max_scan_zoom: 10
    strategy: "grid"

# Terrain DEM service (example)
Terrain_DEM:
  path: "/terrain/:z/:x/:y"
  target: "https://example-terrain.com/dem/{z}/{x}/{y}.png"
  minzoom: 1
  maxzoom: 15
  miss_timeout: 300
  miss_max_records: 10000
  headers:
    request:
      User-Agent: "Mozilla/5.0"
    response:
      Cache-Control:
        max-age:
          hit: 86400
          miss: 300
  query_params:
  mbtiles_file: "terrain_dem.mbtiles"
  metadata:
    bounds: "-180,-85.0511,180,85.0511"
    center: "0,0,4"
    type: "overlay"
    encoding: "terrarium"
  autoscan:
    enabled: false
    daily_limit: 10000
    max_scan_zoom: 10
    strategy: "grid"

# Open source map service
OSM:
  path: "/osm/:z/:x/:y"
  target: "https://example-osm.org/tiles/{z}/{x}/{y}.png"
  minzoom: 1
  maxzoom: 19
  miss_timeout: 300        # 5 minutes timeout for error tiles
  miss_max_records: 10000  # max miss records before cleanup
  headers:
    request:
      User-Agent: "TileProxy/1.0"  # Required by some services
    response:
      Cache-Control:
        max-age:
          hit: 43200      # 12 hours
          miss: 600       # 10 minutes
  query_params:
  mbtiles_file: "openstreetmap.mbtiles"
  metadata:
    bounds: "-180,-85.0511,180,85.0511"
    center: "0,0,4"
    type: "baselayer"  # baselayer | overlay
  autoscan:
    enabled: true
    daily_limit: 10000
    max_scan_zoom: 12
    strategy: "grid"

# Light theme map service
CartoDB_Positron:
  path: "/cartodb/:z/:x/:y"
  target: "https://example-cartodb.com/light/{z}/{x}/{y}.png"
  minzoom: 1
  maxzoom: 18
  miss_timeout: 300        # 5 minutes timeout for error tiles
  miss_max_records: 10000  # max miss records before cleanup
  headers:
  query_params:
  mbtiles_file: "cartodb_positron.mbtiles"
  metadata:
    bounds: "-180,-85.0511,180,85.0511"
    center: "0,0,3"
    type: "baselayer"  # baselayer | overlay

# Custom service with authentication
Custom_Service:
  path: "/custom/:z/:x/:y"
  target: "https://your-tile-service.com/tiles/{z}/{x}/{y}.png"
  minzoom: 0
  maxzoom: 22
  miss_timeout: 300        # 5 minutes timeout for error tiles
  miss_max_records: 10000  # max miss records before cleanup
  headers:
    request:
      Authorization: "Bearer your-access-token"
      X-API-Version: "v2"
    response:
      Cache-Control:
        max-age:
          hit: 3600       # 1 hour
          miss: 60        # 1 minute
  query_params:
    apikey: "your-api-key"
    format: "png"
  mbtiles_file: "custom_service.mbtiles"
  metadata:
    bounds: "-180,-85.0511,180,85.0511"
    center: "0,0,5"
    type: "baselayer"  # baselayer | overlay

# High-resolution tiles service
High_Res_Tiles:
  path: "/highres/:z/:x/:y"
  target: "https://example-highres.com/tiles/{z}/{x}/{y}@2x.png"
  minzoom: 1
  maxzoom: 20
  miss_timeout: 300        # 5 minutes timeout for error tiles
  miss_max_records: 10000  # max miss records before cleanup
  headers:
    request:
      Accept: "image/png,image/webp"
    response:
      Cache-Control:
        max-age:
          hit: 172800     # 48 hours
          miss: 1800      # 30 minutes
  query_params:
    scale: "2x"
  mbtiles_file: "high_res_tiles.mbtiles"
  metadata:
    bounds: "-180,-85.0511,180,85.0511"
    center: "0,0,3"
    type: "baselayer"  # baselayer | overlay

# LERC elevation data service
LERC_Elevation:
  path: "/lerc/:z/:x/:y"
  target: "https://example-lerc.com/elevation/tiles/{z}/{y}/{x}"
  source_format: "lerc"    # Enable LERC processing
  minzoom: 1
  maxzoom: 15
  miss_timeout: 300        # 5 minutes timeout for error tiles
  miss_max_records: 10000  # max miss records before cleanup
  headers:
    request:
      User-Agent: "TileProxy/1.0"
    response:
      Cache-Control:
        max-age:
          hit: 86400      # 24 hours
          miss: 300       # 5 minutes
  query_params:
  mbtiles_file: "lerc_elevation.mbtiles"
  metadata:
    bounds: "-180,-85.0511,180,85.0511"
    center: "0,0,4"
    type: "overlay"       # baselayer | overlay
    encoding: "mapbox"    # Output format for MapLibre compatibility
  autoscan:
    enabled: false
    daily_limit: 5000
    max_scan_zoom: 10
    strategy: "grid"
