source 'https://rubygems.org'

gem 'sinatra'
gem 'slim'
gem 'async'
gem 'sequel'
gem 'pg'
gem 'sqlite3'
gem 'autoforme'

gem 'rack', '~> 3.1.13'
gem 'rackup', '~> 2.2.1'
gem 'falcon'

gem 'stack-service-base'
#, path: '/home/user/projects/stack-service-base'

gem 'maplibre-preview'
#, path: '/home/user/projects/maplibre-preview'

gem 'ffi'
gem 'chunky_png'
gem 'faraday'
# gem 'faraday-net_http'  # or just rely on the default adapter
gem 'faraday-retry'
gem 'faraday-net_http_persistent'

group :test do
  gem 'rspec'
  gem 'rack-test'
  gem 'rspec-benchmark'
  gem 'rspec_junit_formatter'
  gem 'async-rspec'

  gem 'simplecov'
  # gem 'simplecov-cobertura'
  gem 'yard'
end